// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU7hcYo3pnF9yHAYNEzOKfK1iroazFXmA',
    appId: '1:918888511928:web:94d30e9bddc3bfb34bb74d',
    messagingSenderId: '918888511928',
    projectId: 'tinta-y-hojas',
    authDomain: 'tinta-y-hojas.firebaseapp.com',
    storageBucket: 'tinta-y-hojas.firebasestorage.app',
    measurementId: 'G-7KWN2EJHW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi_VkXKXnQhYcNQyKOIDFl3gkAAamdz30',
    appId: '1:918888511928:android:5f10bd4d3289838d4bb74d',
    messagingSenderId: '918888511928',
    projectId: 'tinta-y-hojas',
    storageBucket: 'tinta-y-hojas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuQGF-TUEvryAYPBh6OVuCT0-i9r_puoA',
    appId: '1:918888511928:ios:11c897d4bf7dd9984bb74d',
    messagingSenderId: '918888511928',
    projectId: 'tinta-y-hojas',
    storageBucket: 'tinta-y-hojas.firebasestorage.app',
    iosBundleId: 'com.tintayhojas.tintaYHojas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuQGF-TUEvryAYPBh6OVuCT0-i9r_puoA',
    appId: '1:918888511928:ios:11c897d4bf7dd9984bb74d',
    messagingSenderId: '918888511928',
    projectId: 'tinta-y-hojas',
    storageBucket: 'tinta-y-hojas.firebasestorage.app',
    iosBundleId: 'com.tintayhojas.tintaYHojas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU7hcYo3pnF9yHAYNEzOKfK1iroazFXmA',
    appId: '1:918888511928:web:9454c721c4638e054bb74d',
    messagingSenderId: '918888511928',
    projectId: 'tinta-y-hojas',
    authDomain: 'tinta-y-hojas.firebaseapp.com',
    storageBucket: 'tinta-y-hojas.firebasestorage.app',
    measurementId: 'G-KJ8Y4175QF',
  );
}
